# Generated by Django 2.1.5 on 2020-12-06 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='cartline',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='cartline',
            unique_together={('cart', 'product_variant')},
        ),
    ]
